name: Build Node.js project

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Client/**"
      - ".github/workflows/client/**"
  pull_request_target:
    branches:
      - main
    paths:
      - "Client/**"
      - ".github/workflows/client/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: Client/package-lock.json
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache node_modules
        uses: actions/cache@v4.2.0
        with:
          path: |
            ~/.npm
            Client/node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('Client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - run: cd Client && npm ci
      - run: cd Client && npm run build --if-present
      - run: cd Client && npm test

      - name: Cache Angular build output
        uses: actions/cache@v4.2.0
        with:
          path: Client/dist
          key: ${{ runner.os }}-angular-dist-${{ hashFiles('**/src/**/*') }}
          restore-keys: |
            ${{ runner.os }}-angular-dist-
